### ISSUE TITLE
CAT kit testing

### ISSUE THREAD

**Issue by CindyTribuzio-NOAA** [tristan-sebens/metl#83] opened 2024-07-24 23:52 UTC
1) (May be a Katy question) Lotek 1400-1800 JJ719 has two files in the folder and threw an error. Not sure which file is correct?

2) MTX tags.....I had previously run 118356 with no issues uploading (both recovered and transmitted). The three new tags all failed with error: 'path' must be a string. I did test run both versions of 118356 again with no problems.

**Comment by CindyTribuzio-NOAA** [comment] 2024-07-24 23:54
Example code: 
```
 # MTX recovered----
 decoder = metl::decoders$Decoder_MicrowaveTelemetry_XTag_Recovered
 tag_data_directory = here::here('C://Users/cindy.Tribuzio/Work/temp_folder/Tagging/metl_testingdata/kit_CAT/Microwave elemetry/X-Tag/Recovered/Spiny Dogfish/118367') 
 if(!dir.exists(tag_data_directory)) stop("Data directory does not exist")
 meta = 
   data.frame(
     tag_num = "118367", #note that this is sec_tag_num in db
     tag_type = "AR"
   )
 decoder$decode_to_db(d = tag_data_directory, con = db_conn, meta = meta) #fails
```

Output
```
Error: `path` must be a string
```

**Comment by tristan-sebens** [comment] 2024-09-06 06:56
1. I looked into this issue and determined that yes, this was a matter of misformatted files. Not sure how they got into the format they're in, but it's definitely different than the standard output for Lotek LAT 1400/1800 tags.

2. I wasn't able to reproduce this issue. All data extracted as expected from all three directories (transmitted and recovered). However, there have been two updates since this issue was reported, so it likely just got resolved by one of the patches.

**Closed as completed by tristan-sebens** 2024-09-06 06:56 UTC
Labels: bug, question, tag
